server:
  port: 9000  # 9000번 포트로 실행

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.cwlfftvmude1.ap-northeast-2.rds.amazonaws.com/capstone
    username: admin
    password: rds_nick12
    driver-class-name: com.mysql.cj.jdbc.Driver
